#!/usr/bin/env python

import pytest
import stvalidate
import os
import argparse
import ConfigParser

def main(args):
    config_abs_path = os.path.abspath(args.config_file)
    if not os.path.isfile(config_abs_path):
        raise ValueError(args.config_file+' is not a path to a config file')
    starting_dir = os.getcwd()
    #run from the module root directory for prettier output
    os.chdir(os.path.dirname(stvalidate.__file__))
    pytest_args = ['-v', '--config_file='+config_abs_path]
    config = ConfigParser.ConfigParser()
    config.read(config_abs_path)
    if config.has_option("options","tests"):
        pytest_args.append('-k '+config.get("options","tests"))

    pytest_args.append('test_pipeline.py')
    pytest.main(pytest_args)
    print("returning to "+starting_dir)
    os.chdir(starting_dir)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Test the JWST calibration pipeline')
    parser.add_argument('config_file')
    args = parser.parse_args()
    main(args)